#:schema node_modules/wrangler/config-schema.json
name = "open-essex-officialsite"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "open-essex-db"
database_id = "73117cdd-8f7e-47b7-8d5b-75f998e044de"
